# Generated by Django 5.2.4 on 2025-08-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_customuserprofile_age_customuserprofile_firebase_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='dob',
            field=models.DateField(blank=True, help_text="User's date of birth (DOB).", null=True),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number.", max_length=32, null=True),
        ),
    ]
