# Generated by Django 5.2.4 on 2025-08-23 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_customuserprofile_dob_customuserprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='dob',
            field=models.DateField(blank=True, help_text="User's date of birth.", null=True),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number in E.164 or local format.', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +15551234567).', regex='^\\+?[0-9()\\-\\s]{7,20}$')]),
        ),
    ]
